"""update Role enum values

Revision ID: 7f37ef01ef87
Revises: 5f2c9e1a4567
Create Date: 2025-07-27 15:43:05.890782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f37ef01ef87'
down_revision: Union[str, Sequence[str], None] = '5f2c9e1a4567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_transcriptions_celery_task_id'), table_name='transcriptions')
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_table('settings')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('token_price_at_transaction', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), nullable=False),
    sa.Column('language', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('raw_result_text', sa.TEXT(), nullable=True),
    sa.Column('ai_result_text', sa.TEXT(), nullable=True),
    sa.Column('final_result_text', sa.TEXT(), nullable=True),
    sa.Column('processing_duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('ai_token_usage', sa.INTEGER(), nullable=True),
    sa.Column('output_filename_txt', sa.VARCHAR(), nullable=True),
    sa.Column('output_filename_docx', sa.VARCHAR(), nullable=True),
    sa.Column('celery_task_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('display_filename', sa.VARCHAR(), server_default=sa.text("'file'"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    op.create_index(op.f('ix_transcriptions_celery_task_id'), 'transcriptions', ['celery_task_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('total_calls', sa.INTEGER(), nullable=True),
    sa.Column('total_tokens_used', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=1)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('file_limit', sa.INTEGER(), nullable=True),
    sa.Column('daily_transcription_count', sa.INTEGER(), nullable=True),
    sa.Column('last_transcription_date', sa.DATE(), nullable=True),
    sa.Column('wallet_balance', sa.FLOAT(), nullable=True),
    sa.Column('token_price', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###
